M5Stack Core2 for AWS専用STLファイルを共有致します
meganetaaan/stack-chan pull request #137
Opened 2023-03-14 16:04 UTC by ToshihiroMakuuchi

今回、M5Stack Core2 for AWSを用いてｽﾀｯｸﾁｬﾝを構成していますが、ケース(ボディ)等の最適化を試みました。素材との相性もある事、あくまでもfor AWSに特化した加工もしております為、ご利用は自己責任でお願い致します。

2023-03-16 03:00 UTC, meganetaaan requested changes
プルリクエストありがとうございます！
ドローン界隈の方にも興味を持っていただけて、とても嬉しいです。

軽微な指摘が数点ありますので、ご確認お願いします。

2023-03-16 03:00 UTC, meganetaaan commented on case/contributed/HS_Glide_Path_case for_SG90_and_M5Stack_AWS/README_for_SG90andM5StackAWS_ja.md
> +日本語 | [English](./README_for_SG90andM5StackAWS.md)
英語版ドキュメントの追加をお願いします。機械翻訳レベルで構いません。

2023-03-16 03:00 UTC, meganetaaan commented on case/contributed/HS_Glide_Path_case for_SG90_and_M5Stack_AWS/README_for_SG90andM5StackAWS_ja.md
> +このモデルは、M5Stack Core2 for AWS - ESP32 IoT開発キットに合わせ、皆さんのCASEモデルに修正を加えたものです。
修正元のモデルへのリンク（相対パス）を追加お願いします。

修正元のデータは紅木タカオさんのこちらのケースで合ってますか？
https://github.com/meganetaaan/stack-chan/blob/dev/v1.0/case/contributed/mongonta_case_for_SG90_and_M5GoBottomBoard/case_for_SG90andM5GoBottomBoard/shell_SG90_gobottom.stl

2023-03-16 03:00 UTC, meganetaaan commented on case/contributed/HS_Glide_Path_case for_SG90_and_M5Stack_AWS/README_for_SG90andM5StackAWS_ja.md
> +# サーボの挙動に関して
この章はぜひDiscussionに移して議論してみませんか！？

https://github.com/meganetaaan/stack-chan/discussions

31~37行目をまるごとカットアンドペーストでよいので。

2023-03-16 14:05 UTC, ToshihiroMakuuchi commented on case/contributed/HS_Glide_Path_case for_SG90_and_M5Stack_AWS/README_for_SG90andM5StackAWS_ja.md
> +このモデルは、M5Stack Core2 for AWS - ESP32 IoT開発キットに合わせ、皆さんのCASEモデルに修正を加えたものです。
はい、その通りです。
相対パスは

[既存のケースモデル](stack-chan/case/contributed/mongonta_case_for_SG90_and_M5GoBottomBoard/case_for_SG90andM5GoBottomBoard/shell_SG90_basicgraybottom.stl)

こんな感じで、stack-chan始まりのパスで埋めましたが・・・これで良いですか？

2023-03-16 14:15 UTC, ToshihiroMakuuchi commented on case/contributed/HS_Glide_Path_case for_SG90_and_M5Stack_AWS/README_for_SG90andM5StackAWS_ja.md
> +# サーボの挙動に関して
こちら、透過しましたー

2023-03-21 03:17 UTC, merged

2023-03-21 03:18 UTC, meganetaaan commented on case/contributed/HS_Glide_Path_case for_SG90_and_M5Stack_AWS/README_for_SG90andM5StackAWS_ja.md
> +このモデルは、M5Stack Core2 for AWS - ESP32 IoT開発キットに合わせ、皆さんのCASEモデルに修正を加えたものです。
追加ありがとうございます！相対パスが間違っていたのでこちらで修正しちゃいました😀