add unit_temperature mod
meganetaaan/stack-chan pull request #208
Opened 2023-09-17 05:07 UTC by stc1988

#98 のM5stack Unitを使用したmodの例になります。

手元では[ENV II](https://docs.m5stack.com/en/unit/envII)で確認しましたが、ENV IIIでも同様に温湿度センサSHT30を搭載しているため使用可能と思います。

本mod追加にあたり、１点Host側にも変更を追加しています。
多くのセンサは[CRC](https://github.com/Moddable-OpenSource/moddable/tree/c2d0b356e9d0e64f50d954acb42b02d325f533b9/modules/data/crc)を参照しており、そこではC言語実装をしているため、modの制約より`mcrun`でコンパイルエラーとなります。
そこで、Host側で事前にCRCをインクルードしてmod側ではdriverモジュール単体を読み込むようにしています。CRCの規模は大きくないため、Host側のサイズに大きな影響は無いと考えています。

***
動作の様子
https://x.com/stc1988/status/1703041218647871841?s=20

2023-09-19 04:39 UTC, meganetaaan requested changes

2023-09-19 04:39 UTC, meganetaaan commented on firmware/mods/unit_temperature/mod.js
> +    const balloon = createBalloonDecorator({
`Robot#showBalloon`, `Robot#hideBalloon`を追加しました。ちょうどこのmodで行っているフキダシの表示、非表示が簡単に書けます。modではこちらを推奨します。

```js
import Humidity from 'embedded:sensor/Humidity-Temperature/SHT3x'
import Timer from 'timer'

Timer.delay(200)
const sensor = new Humidity({ sensor: device.I2C.default })

const param = {
  right: 20,
  top: 10,
  width: 200,
}

export function onRobotCreated(robot) {
  const targetLoop = () => {
    const sample = sensor.sample()
    robot.showBalloon(
      `Temperature: ${sample.thermometer.temperature.toFixed(2)} C. 
      Humidity: ${sample.hygrometer.humidity.toFixed(2)} %`,
      param
    )
    Timer.set((_id) => robot.hideBalloon(), 10 * 1000)
  }
  Timer.set(targetLoop, 3 * 1000, 60 * 1000)
}
```

2023-09-19 13:02 UTC, stc1988 commented on firmware/mods/unit_temperature/mod.js
> +    const balloon = createBalloonDecorator({
レビューありがとうございます。
そのほかdelayやparamの指摘も含めて取り込みました。

2023-09-20 12:27 UTC, meganetaaan commented on firmware/mods/unit_temperature/mod.js
> +    const balloon = createBalloonDecorator({
変更ありがとうございます。LGTMです🙆

2023-09-20 12:28 UTC, meganetaaan approved these changes

2023-09-20 12:28 UTC, merged