Integrate AI Stack-chan Web API
meganetaaan/stack-chan pull request #235
Opened 2024-01-04 06:22 UTC by ronron-gh

こちらのIssueについてのプルリクエストです。
#204 

主な変更内容は次の通りです。
・Modとしてai-stackchan-apiを追加
・Web版VOICEVOXを firmware/stackchan/speeches に追加 (tts-voicevox-web.ts)

詳しい実行のしかたは mods/ai-stackchan-api/README_ja.md に記載しています。

備考（TTSについて）
・Web版VOICEVOXは若干途切れることはありますが安定しています。ただ、音声再生開始に30秒程度かかるため調査中です。  
・Elevenlabsも使えますが、[issue#214](https://github.com/meganetaaan/stack-chan/issues/214)はこちらでも再現しています。

2024-01-04 12:28 UTC, stc1988 commented
遅い原因について確認してみましたが、APIを実行する際の[SSLのhandashake処理](https://github.com/Moddable-OpenSource/moddable/blob/public/modules/crypt/ssl/ssl_handshake.js#L862-L877)に時間がかかっているようです。
解決の糸口が見えてないですが共有まで。

![image](https://github.com/meganetaaan/stack-chan/assets/11245747/a3db0d77-7c44-4be1-8c20-da1638368f95)

2024-01-04 15:13 UTC, ronron-gh commented
確認してくださりありがとうございます。xsbugで時間計測できるのですね。SSLに関係するところを調べてみます。

2024-01-05 02:32 UTC, ronron-gh commented
教えていただいた通り、[SSLのhandashake処理](https://github.com/Moddable-OpenSource/moddable/blob/public/modules/crypt/ssl/ssl_handshake.js#L862-L877) の、DH_RSAの計算に時間がかかっていることを、こちらでも確認できました。一行ずつ実行すると、特にmod.exp() に時間がかかっているようです。
Elevenlabsでは ECDHE_RSA が使われるようで、それほど時間はかかりません。
暗号化方式を選べればよいのですが...（SSLは詳しくないのでもう少し勉強が必要です。）

2024-01-05 09:04 UTC, stc1988 commented
https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/network/securesocket.md

ここにも時間がかかると書いてありました。と、動くが見れてないですがconfigでオフにもできるようです

2024-01-05 12:39 UTC, stc1988 commented
@ronron-gh 
manifestファイルに以下追記で改善されているように見えますので、ご確認のほどよろしくお願いします

```
"config": {
        "tls": {
            "DHE_RSA": false
        }
    }
```

2024-01-05 16:42 UTC, ronron-gh commented
@stc1988 
ありがとうございます、ドキュメントを見ればよかったのですね。大変助かりました。こちらでも改善が確認できたため、コミットしました。（speeches/manifest_https_mp3streamer.json）
ただ、VOICEVOXでも音声が長くなると途切れ途切れになりますね。これはElevenlabsと合わせて[issue#214](https://github.com/meganetaaan/stack-chan/issues/214)で対策したく思います。

2024-02-07 16:22 UTC, meganetaaan requested changes
PRの作成ありがとうございます！
手元で動作確認してコードレビューを実施しました。
ｽﾀｯｸﾁｬﾝconnectから操作できて感動です。

何点か、修正いただきたい点についてコメントしました。対応できそうでしたら修正をお願いします。不明点あればお知らせください。

2024-02-07 16:22 UTC, meganetaaan commented on firmware/mods/ai_stackchan_api/mod.js
> +  server.callback = function (message, value, value2) {
ここは本家と挙動を揃えるためにぜひ非同期化したいですね。うまく実装するとチャットの返答をレスポンスとして返せるかと思います。
async/awaitベースのサーバ実装としてModdable側サンプルの[`examples/io/listen`](https://github.com/Moddable-OpenSource/moddable/blob/public/examples/io/listener/listen/main.js)が使えそうです。

2024-02-07 16:22 UTC, meganetaaan commented on firmware/stackchan/speeches/tts-voicevox-web.ts
> +    this.audio = new AudioOut({ streams: 1, bitsPerSample: 16, sampleRate: 22050 })
コンストラクタ引数`props.sampleRate`をAudioOutのコンストラクタに渡すようお願いします。[tts-voicevoxの実装](https://github.com/meganetaaan/stack-chan/blob/5045acb68fc73a5e9ccb3520eb687b3407164d85/firmware/stackchan/speeches/tts-voicevox.ts#L39)が参考になります。

2024-02-07 16:22 UTC, meganetaaan commented on firmware/stackchan/manifest.json
> +        "$(MODULES)/network/http/manifest.json",
追加のマニフェストですが、ｽﾀｯｸﾁｬﾝのマニフェストは機能毎に分割して読み込む作りにしてあります。AIｽﾀｯｸﾁｬﾝサーバは機能としては`service`に当たると思われます。いずれスクリプト本体もmodから`/stackchan/services/`配下に置くことを想定して、`/stackchan/services/manifest_service.json`に書くと良いです。

2024-02-07 16:22 UTC, meganetaaan commented on firmware/stackchan/speeches/tts-voicevox-web.ts
> +    await this.getQuery(key, speakerId)
`streamUrl`はTTSクラスのメンバ変数にする必要は無さそうに思います。

```js
const streamUrl = await getQuery(/* 引数 */)
```

のようにできると良さそうです。
ただこのとき、今の実装ではgetQueryに失敗した場合の戻り値が空になるのが問題となりますね。
取りうる対策としては、

* getQuery内のcatch文を削除してstringを返す関数として定義する

```typescript
  async getQuery(text: string, speakerId = 1): Promise<string> {
    return fetch(encodeURI(`https://api.tts.quest/v3/voicevox/synthesis?key=${this.token}&text=${text}&speaker=${speakerId}`))
      .then((response) => {
        return response.json()
      })
      .then((data) => {
        trace(`isApiKeyValid: ${data.isApiKeyValid}\n`)
        trace(`mp3StreamingUrl: ${data.mp3StreamingUrl}\n`)
        this.streamUrl = data.mp3StreamingUrl
        return data.mp3StreamingUrl
      })
  }
```

* getQueryを使う側で例外をキャッチして、`Error`を上げ直す

```typescript
const streamUrl = await getQuery(/* 引数 */).catch((error) => {
  throw new Error(`getQuery failed: ${e}`)
})
```

このようにするとgetQueryが異常なく終了した時にstreamUrlにstringが入ることが保証されます。

2024-02-07 23:23 UTC, stc1988 commented
先日マージされた#236 で最新のModdableで動くような修正を行いましたので、本対応のブランチへ取り込み頂けると幸いですし、実装の方もお手伝いできます

2024-02-08 13:26 UTC, ronron-gh commented
@meganetaaan 
ご確認誠にありがとうございました。これから一つ一つ対応していきます。

@stc1988 
最新のマージについて了解しました。まずは取り込んでみます。サポートいただけるのは大変心強いです。

2024-02-09 16:11 UTC, ronron-gh commented
まずは #236 をマージしてコミットしました。自分の開発環境のModdable SDKを4.4にアップデートして、動くことを確認しました。（コミットのコメントが4.1に対応となっていますが4.4の間違いです。）

2024-02-10 05:00 UTC, stc1988 commented
最新の取り込みありがとうございます。
サーバの方はlistenベースにasync-awaitが使えるものをserviceとして追加します

2024-02-11 08:32 UTC, ronron-gh commented on firmware/stackchan/speeches/tts-voicevox-web.ts
> +    this.audio = new AudioOut({ streams: 1, bitsPerSample: 16, sampleRate: 22050 })
props.sampleRate を渡すように修正してコミットしました。

2024-02-11 08:41 UTC, ronron-gh commented on firmware/stackchan/speeches/tts-voicevox-web.ts
> +    await this.getQuery(key, speakerId)
上記の通り修正し、TTSが正常動作することを確認しました（コミット済み）。
ただ、わざと誤ったURLにして実行してみましたが、例外が発生しませんでした。元のコードに戻しても同じだったため、この修正が原因というわけではありません。

2024-02-11 08:45 UTC, ronron-gh commented on firmware/mods/ai_stackchan_api/mod.js
> +  server.callback = function (message, value, value2) {
ご提案いただいたasync/awaitベースのサーバをserviceとして実装するように、stc1988さんにサポートいただきながら対応中です。

2024-02-11 09:18 UTC, stc1988 commented
@ronron-gh さんのリポジトリにサーバ機能などのPR上げているので、ご確認ください

2024-02-11 13:38 UTC, ronron-gh commented
@stc1988 
ありがとうございます！今確認しました。
メール通知がされなかったため気づいていませんでした。この会話は通知されるのですが...

2024-02-12 02:29 UTC, stc1988 commented
https://x.com/stc1988/status/1756866287849148524?s=20

台詞と会話が動くようになりました。
他のAPIエンドポイントはhost側の実装の整理も必要そうなので、いったんここまでで止めています

2024-02-12 03:28 UTC, ronron-gh commented
ありがとうございます！！自分も、作っていただいたサービスをModに取り込もうとしていましたが、TypeScriptの基本的なところではまっていました^^;

2024-02-13 13:53 UTC, stc1988 commented
マージいただいてレビュー対応済みになります

2024-02-13 14:12 UTC, ronron-gh commented on firmware/mods/ai_stackchan_api/mod.js
> +  server.callback = function (message, value, value2) {
stc1988さんにサーバの実装をasync/awaitベースに修正していただき、動作確認とマージが完了しました。

2024-02-13 14:13 UTC, ronron-gh commented on firmware/stackchan/manifest.json
> +        "$(MODULES)/network/http/manifest.json",
stc1988さんによってサーバ機能を service として実装していただき、対応完了しました。

2024-02-13 14:22 UTC, ronron-gh commented
@meganetaaan 
stc1988さんに対応いただいた部分をマージして、コードレビューにすべて回答できましたので、ご確認のほどよろしくお願いいたします。

2024-02-29 16:05 UTC, meganetaaan approved these changes
LGTMです！手元で「会話」「台詞」「表情」機能が正しく動作することを確認できました！

2024-03-01 02:27 UTC, merged

2024-03-01 02:29 UTC, meganetaaan commented on firmware/stackchan/speeches/tts-voicevox-web.ts
> +    await this.getQuery(key, speakerId)
本件別のissue立てて確認しますね。

2024-03-01 07:28 UTC, stc1988 commented on firmware/stackchan/speeches/tts-voicevox-web.ts
> +    await this.getQuery(key, speakerId)
再現見て頂いたら良いですが、確か直してしまった気がします

2024-03-01 07:29 UTC, stc1988 commented on firmware/stackchan/speeches/tts-voicevox-web.ts
> +    await this.getQuery(key, speakerId)
リファクタリングっぽい対応に混ざってます…

https://github.com/meganetaaan/stack-chan/commit/b0f570c49a1823e2156e1bfbe2cb2646eb1a66ea

2024-03-02 07:46 UTC, meganetaaan commented on firmware/stackchan/speeches/tts-voicevox-web.ts
> +    await this.getQuery(key, speakerId)
見ました。直ってますね！OKです :ok_person: