AIｽﾀｯｸチャン機能
meganetaaan/stack-chan pull request #302
Opened 2024-10-12 16:21 UTC by stc1988

STT -> LLM -> TTS を使った一連の所謂AIｽﾀｯｸﾁｬﾝ実現に必要な機能追加のPRです。

大きな機能追加ごとにコミットを分けており、その概要と実装途中で気になったこと、本PRで議論したいことを記載してます。

## STT追加

- OpenAIのwhisperをSTTとして利用できるようにしています
- WAVファイルを受け取り、whisperのAPIを実行して文字起こし結果を応答する機能となっています。
- testアプリを用意しており、同フォルダのサンプルWAVファイルで動作確認が可能です。

今回STTクラスを新規追加するので、STTクラスのインターフェース仕様について確認をいただきたいです

## Micorphone追加

- AudioInを使った録音機能が実行できます
- デフォルトでは3秒間録音し、WAVファイル形式で応答します。
  - 秒数を増やす場合には、`creation`でのメモリ確保量を増やす必要があるかもしれません。
- 現在マイクが利用可能なCore2のみ対応としてます
- robotクラスからは`record`メソッドとして利用可能になっています。
   - STTを実行するにはSTTクラスとの組み合わせが必要
  
robotクラスとして公開するメソッドの追加は`record`のみですが、STTクラスと組み合わせメソッドを用意した方が良いかなど、robotクラスの拡張方針を確認いただきたいです

## mods/ai_stackchan 追加

- STT -> LLM -> TTS を使った一連を実行します。

今回追加した機能の想定する使い方となっています。modアプリケーションの書き振りで気になるところがあればコメントをいただきたいです

2024-10-13 03:42 UTC, stc1988 commented
すみません、modの本体コミット漏れていたので追加しました

2024-10-14 13:19 UTC, meganetaaan requested changes
まだ実機で動作確認できていませんが、 `test`を使ってSTTは確認できました。
I/Fと実装で気になった点をコメントしました。

2024-10-14 13:19 UTC, meganetaaan commented on firmware/mods/ai_stackchan/mod.js
> +      robot.tone(1000, 100)
```suggestion
      await robot.tone(1000, 100)
```

2024-10-14 13:19 UTC, meganetaaan commented on firmware/mods/ai_stackchan/mod.js
> +    robot.tone(600, 100)
```suggestion
    await robot.tone(600, 100)
```

2024-10-14 13:19 UTC, meganetaaan commented on firmware/stackchan/microphone.ts
> +  async record(durationSec = 3): Promise<ArrayBuffer> {
秒数の単位がRobotの中でバラバラだったので、これを機に `ミリ秒に統一` したいと思いますので修正いただけますでしょうか。

- `Timer`がミリ秒ベース
- Moddableの内部処理的にIntが使われて計算効率が良い

Robotの他の単位の修正は別PRでできればと思います。

2024-10-14 13:19 UTC, meganetaaan commented on firmware/stackchan/microphone.ts
> +          const samples = new Int16Array(audio.read(sampleCount))
`audio.read` の[第二引数にバッファ](https://github.com/Moddable-OpenSource/moddable/blob/978945595c6aaa460c6068b34d3ebc415db248a7/modules/pins/audioin/esp32/audioin.c#L223)、[第三引数にオフセット](https://github.com/Moddable-OpenSource/moddable/blob/978945595c6aaa460c6068b34d3ebc415db248a7/modules/pins/audioin/esp32/audioin.c#L219)を渡せるようです。
下記のようにするとメモリ効率が良くなりそうですがいかがでしょうか。

```
const buffer = new ArrayBuffer(44 + contentLength)
const view = new DataView(buffer)
// ...
let offset = 44;
Timer.repeat((id) => {
  audio.read(sampleCount, buffer, offset)
  offset += 2
  // ...
}, 1000 / readingsPerSecond)
```

この関数、[型定義](https://github.com/Moddable-OpenSource/moddable/blob/978945595c6aaa460c6068b34d3ebc415db248a7/typings/pins/audioin.d.ts#L25)と齟齬があるのでModdable側の修正も合わせて必要ですね。
本件に限らず型の修正は、

- 一旦stack-chan側のコードに `//@ts-ignore` フラグを付けてビルドを通す
- Moddable側にPRを出す
- Moddable側が修正、リリースされたらフラグを外す

という進め方が良さそうに思いました。

2024-10-14 13:19 UTC, meganetaaan commented on firmware/stackchan/transcriptions/stt-whisper.ts
> +  async transcription(audio: ArrayBuffer | HostBuffer): Promise<Maybe<string>> {
I/Fは良いと思います。
長期的にはアップロード中に逐次AudioInから読み取って送信ができると理想的です。
（WavStreamerの逆をやるイメージです）
そうすると、送信時間 < 読み出しにかかる時間 である限り好きなだけ送信できるようになります。

2024-10-14 13:19 UTC, meganetaaan commented on firmware/stackchan/transcriptions/stt-whisper.ts
> +  async transcription(audio: ArrayBuffer | HostBuffer): Promise<Maybe<string>> {
- 動詞形（transcribe）にする
- 引数名は、 `audioOut`等との混同を避けるために `audioBuffer`または単に `buffer` などとする

```suggestion
  async transcribe(audioBuffer: ArrayBuffer | HostBuffer): Promise<Maybe<string>> {
```

2024-10-14 13:19 UTC, meganetaaan commented on firmware/mods/ai_stackchan/mod.js
> +      await robot.say('わかりません！')
良いですね〜〜 :ok_woman: :ok_woman: :ok_woman:

2024-10-14 13:23 UTC, meganetaaan commented
>robotクラスとして公開するメソッドの追加はrecordのみですが、STTクラスと組み合わせメソッドを用意した方が良いかなど、robotクラスの拡張方針を確認いただきたいです

はい！ご認識のとおり、長期的には録音＋STTを同時に行うメソッドを1個用意したいと考えています。というのも、レビューコメントにもあるとおり一旦bufferへの保存を挟まずに直接STTサーバに送れるとメモリ効率が格段によくなるためです。

`robot#say` の逆をやるイメージです。

```ts
class Robot {
  async listen(void): Promise<Maybe<string>> () {}
}
```

2024-10-14 13:38 UTC, stc1988 commented
@meganetaaan 
ご確認ありがとうございます。

メモリ効率と他に録音が必要な機能のために録音周りは、ちょうどECMA-419のAudioInが公開されたので、これを適用時に整理はしたいですね。

> はい！ご認識のとおり、長期的には録音＋STTを同時に行うメソッドを1個用意したいと考えています。というのも、レビューコメントにもあるとおり一旦bufferへの保存を挟まずに直接STTサーバに送れるとメモリ効率が格段によくなるためです。

これを実現しようと思うとSTTをTTS同様にrobotに登録した方が良さそうでしょうか。

2024-10-15 07:17 UTC, stc1988 commented on firmware/stackchan/microphone.ts
> +          const samples = new Int16Array(audio.read(sampleCount))
https://github.com/Moddable-OpenSource/moddable/blob/public/modules/pins/audioin/sim/audioin.js

確かにsim側で定義みると引数設定できますね…。動作確認して問題無さそうであれば、型定義更新っしつつの方針とします

2024-10-20 11:51 UTC, stc1988 commented on firmware/stackchan/transcriptions/stt-whisper.ts
> +  async transcription(audio: ArrayBuffer | HostBuffer): Promise<Maybe<string>> {
そうですね。robot側にも随時AudioInから読み取った値を返すI/Fを提供しつつ、transcribeも内部的にはそれを利用する形には将来的にはもっていきたいです。

2024-10-20 11:53 UTC, stc1988 commented on firmware/stackchan/microphone.ts
> +          const samples = new Int16Array(audio.read(sampleCount))
型定義は以下でPR作成済みですが、ts-ignoreして動作確認できました
https://github.com/Moddable-OpenSource/moddable/pull/1424

2024-10-20 12:13 UTC, stc1988 commented
中長期的な対応項目はありますがひとまず指摘対応ができたので、draftはずして 🐇 レビューにかけてみます

2024-10-20 12:24 UTC, stc1988 commented on firmware/mods/ai_stackchan/mod.js
> +    await robot.say(result.value)
マイコン環境で動作させるため、メモリ消費を抑えるために変数を使いまわしています

2024-10-20 12:26 UTC, stc1988 commented on firmware/stackchan/manifest_microphone.json
> +  }
指定に誤りがあったため、ファイル名に合わせてspeech -> speakとします

2024-10-20 12:29 UTC, stc1988 commented on firmware/mods/ai_stackchan/mod.js
> +      'You are "スタックちゃん(Stack-chan)", the palm sized super kawaii companion robot baby. You must response in a short sentense.',
指摘の通りに修正します

2024-10-20 12:31 UTC, stc1988 commented on firmware/mods/ai_stackchan/mod.js
> +    }
異常発生時は顔を元に戻します

2024-10-20 12:33 UTC, stc1988 commented on firmware/mods/ai_stackchan/mod.js
> +    trace('end recording.\n')
指摘の通り録音失敗にエラーハンドリングを追加しました。

2024-10-20 12:34 UTC, stc1988 commented on firmware/mods/ai_stackchan/mod.js
> +      return
対応しました

2024-10-20 12:40 UTC, stc1988 commented on firmware/mods/ai_stackchan/mod.js
> +}
ありがとうございます。指摘の通り対応しました

2024-10-20 12:55 UTC, stc1988 commented on firmware/stackchan/microphone.ts
> +  }
try-finallyブロックを追加しました

2024-10-20 12:58 UTC, stc1988 commented on firmware/stackchan/microphone.ts
> +          offset += sampleCount
指摘の通り修正して動作が確認できました

2024-10-20 13:01 UTC, stc1988 commented on firmware/stackchan/transcriptions/stt-whisper.ts
> +  }
ありがとう。指摘の通りtry-catchを追加しました

2024-10-21 14:02 UTC, stc1988 commented on firmware/stackchan/transcriptions/stt-whisper.ts
> +        'Content-Type: application/octet-stream\r\n\r\n'
変更すると400エラーとなったので意図通りの指定となります

2024-10-21 14:03 UTC, stc1988 commented
@meganetaaan  🐇 対応も完了しました

2024-10-23 13:54 UTC, meganetaaan approved these changes
Core2本体のみを使って動作確認しました。めっちゃいいですね！コードの修正もLGTMです！

Core2だと裏蓋のマイクが必須なので、CoreS3やPDMマイクユニット後付け等、ｽﾀｯｸﾁｬﾝのボディと合わせて動作できるか試してみます。

2024-10-23 14:10 UTC, merged