Add customized stl files for SG90
meganetaaan/stack-chan pull request #9
Opened 2021-08-01 15:51 UTC by shikarunochi

### Summary
Add stack-chan customized stl files for SG90
- compact bracket
- feet with micro USB

### Tool
DesignSpark Mechanical

2021-08-04 03:51 UTC, meganetaaan requested changes
プルリクありがとうございます！確認しました。

- bracket_SG90_COMPACT.stlはbracket_SG90.stlに __上書き__ していただけますか？フォルダ内が下記のような状態になるイメージです。

```
bracket_SG90.stl （←コンパクト版上書き）
shell_SG90.stl
feet_SG90.stl
feet_SG90_with_microUSB.stl
```

- feet_SG90_with_microUSB.stlのほうはOKです！

2021-08-29 13:32 UTC, shikarunochi commented
すいません、プルリク慣れしていなくて、反応が遅れてしまい申し訳ありません。
bracket_SG90.stl をコンパクト版 stl で上書きしましたー。

2021-08-30 14:11 UTC, meganetaaan approved these changes

2021-08-30 14:11 UTC, merged

2021-08-30 14:12 UTC, meganetaaan commented
確認しました。ありがとうございます！